highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://myjekyll.github.io/vitae
author: Deepak Chauhan

# edit this section with your information
# myjekyll.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Deepak Chuahan's Resume
name: Deepak Chauhan
email: dc84477@gmail.com
email_full: mailto:dc84477@gmail.com
website: mrdeepakchauhan.github.io
website_full: https://mrdeepakchauhan.github.io
github: mrdeepakchauhan
twitter: dc84477
tel: +91 8319787486
tel_full: tel:+918319787486

google_maps: 'https://goo.gl/maps/7c11cbzF2k32'
address:
  street: EWS 22, Power House
  postcode: 490026
  city: Bhilai
  country: India
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
